#!/bin/sh
#
# Run through the clang static analyzer.
#
TARGET=$(dirname $0)/../darkhttpd.c

# Adjust to suit:
LLVM=$HOME/llvm

$LLVM/llvm/tools/clang/tools/scan-build/bin/scan-build \
  -analyze-headers \
  --use-analyzer=$LLVM/install/bin/clang \
  clang -DDEBUG $TARGET
