#!/bin/sh
#
# Build with clang with all warnings.
#
TARGET=$(dirname $0)/../darkhttpd.c

# Adjust to suit:
LLVM=$HOME/llvm

$LLVM/install/bin/clang -Weverything -O \
  -Wno-unreachable-code -Wno-padded -Wno-disabled-macro-expansion \
  -DDEBUG $TARGET
rm -f a.out
